# Generated by Django 5.2 on 2026-08-01 07:25

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('description_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('description_ky', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('icon', models.FileField(blank=True, null=True, upload_to='booking/addons/', verbose_name='Иконка')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 600], upload_to='booking/addons/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена, сом')),
                ('price_type', models.CharField(choices=[('booking', 'За бронь'), ('night', 'За ночь'), ('guest', 'За гостя'), ('guest_night', 'За гостя за ночь')], default='booking', max_length=15, verbose_name='Тип расчёта')),
                ('shelter_code', models.CharField(blank=True, max_length=64, verbose_name='Код услуги в Shelter')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги (при брони)',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Номер брони')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('awaiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачена'), ('confirmed', 'Подтверждена (записана в Shelter)'), ('payment_failed', 'Оплата не прошла'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('room_category_name', models.CharField(blank=True, help_text='Фиксируется на момент брони, чтобы переименование категории не искажало историю.', max_length=255, verbose_name='Название категории (снимок)')),
                ('shelter_room_code', models.CharField(blank=True, max_length=64, verbose_name='Код категории в Shelter')),
                ('rooms_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество номеров')),
                ('check_in', models.DateField(db_index=True, verbose_name='Заезд')),
                ('check_out', models.DateField(db_index=True, verbose_name='Выезд')),
                ('adults', models.PositiveSmallIntegerField(default=2, verbose_name='Взрослых')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Детей')),
                ('children_ages', models.CharField(blank=True, help_text='Через запятую, например: 4, 9', max_length=100, verbose_name='Возраст детей')),
                ('guest_first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('guest_last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('guest_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('guest_country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('comment', models.TextField(blank=True, verbose_name='Пожелания гостя')),
                ('currency', models.CharField(default='KGS', max_length=3, verbose_name='Валюта')),
                ('room_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость проживания')),
                ('addons_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость доп. услуг')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого к оплате')),
                ('prepay_amount', models.DecimalField(decimal_places=2, default=0, help_text='Сколько списывается онлайн. Может быть частью суммы брони.', max_digits=12, verbose_name='Сумма предоплаты')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено')),
                ('shelter_reservation_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID брони в Shelter')),
                ('shelter_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Записана в Shelter')),
                ('shelter_error', models.TextField(blank=True, help_text='Если заполнено — бронь оплачена, но не попала в PMS. Требует ручной обработки.', verbose_name='Ошибка синхронизации с Shelter')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='Язык оформления')),
                ('source', models.CharField(default='website', max_length=50, verbose_name='Источник')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменена')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='offers.promocode', verbose_name='Промокод')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.roomcategory', verbose_name='Категория номера')),
                ('special_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='offers.specialoffer', verbose_name='Спецпредложение')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название (снимок)')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='booking.addon', verbose_name='Услуга')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='booking.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Доп. услуга в брони',
                'verbose_name_plural': 'Доп. услуги в брони',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(default='freedompay', max_length=30, verbose_name='Провайдер')),
                ('order_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Order ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID платежа у провайдера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(default='KGS', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает подтверждения'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменён'), ('refunded', 'Возвращён')], db_index=True, default='created', max_length=15, verbose_name='Статус')),
                ('payment_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на оплату')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='Запрос')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Ответ')),
                ('callback_data', models.JSONField(blank=True, null=True, verbose_name='Колбэк')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='booking_boo_check_i_8846a0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='booking_boo_status_75aeac_idx'),
        ),
    ]
