# Generated by Django 5.2 on 2026-08-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('room_category_name', models.CharField(blank=True, help_text='Сохраняем название на момент заявки — категорию могут переименовать.', max_length=255, verbose_name='Категория (снимок)')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Заезд')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Выезд')),
                ('nights', models.PositiveSmallIntegerField(default=0, verbose_name='Ночей')),
                ('adults', models.PositiveSmallIntegerField(default=2, verbose_name='Взрослых')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Детей')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, help_text='Цена с сайта на момент заявки, не подтверждённая отелем.', max_digits=12, verbose_name='Расчётная сумма')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Откуда отправлена')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='Язык сайта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Браузер')),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='Отметка менеджера: с гостем связались.', verbose_name='Обработана')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('room_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='rooms.roomcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
                'ordering': ('-created_at',),
            },
        ),
    ]
