# Generated by Django 5.2 on 2026-08-01 07:25

import ckeditor_uploader.fields
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_en', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_ky', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO: keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('og_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1200, 630], upload_to='seo/', verbose_name='Изображение для соцсетей (OG)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('excerpt_ru', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('excerpt_en', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('excerpt_ky', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('content_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 900], upload_to='blog/', verbose_name='Обложка')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Блог и новости',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('author_name', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('author_city', models.CharField(blank=True, max_length=255, verbose_name='Город / страна')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[200, 200], upload_to='reviews/', verbose_name='Фото автора')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1–5)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('source', models.CharField(choices=[('site', 'Форма на сайте'), ('booking', 'Booking.com'), ('google', 'Google'), ('2gis', '2GIS'), ('manual', 'Добавлен вручную')], default='site', max_length=20, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка на отзыв')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Одобрен к публикации')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
