# Generated by Django 5.2 on 2026-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID во внешнем сервисе'),
        ),
        migrations.AddField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва'),
        ),
    ]
