# Generated by Django 5.2 on 2026-08-27 07:09

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_review_external_id_review_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(blank=True, help_text='Например: «Гость курорта, Алматы» или должность.', max_length=255, verbose_name='Кто это')),
                ('role_ru', models.CharField(blank=True, help_text='Например: «Гость курорта, Алматы» или должность.', max_length=255, null=True, verbose_name='Кто это')),
                ('role_en', models.CharField(blank=True, help_text='Например: «Гость курорта, Алматы» или должность.', max_length=255, null=True, verbose_name='Кто это')),
                ('role_ky', models.CharField(blank=True, help_text='Например: «Гость курорта, Алматы» или должность.', max_length=255, null=True, verbose_name='Кто это')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=88, scale=None, size=[800, 800], upload_to='guests/', verbose_name='Фото')),
                ('quote', models.TextField(verbose_name='Что сказал')),
                ('quote_ru', models.TextField(null=True, verbose_name='Что сказал')),
                ('quote_en', models.TextField(null=True, verbose_name='Что сказал')),
                ('quote_ky', models.TextField(null=True, verbose_name='Что сказал')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Наши гости',
                'ordering': ('order', '-id'),
            },
        ),
    ]
