# Generated by Django 5.2 on 2026-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='quote',
            field=models.TextField(blank=True, help_text='Необязательно. Карточка работает и без неё — только фото и имя гостя.', verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='quote_en',
            field=models.TextField(blank=True, help_text='Необязательно. Карточка работает и без неё — только фото и имя гостя.', null=True, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='quote_ky',
            field=models.TextField(blank=True, help_text='Необязательно. Карточка работает и без неё — только фото и имя гостя.', null=True, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='quote_ru',
            field=models.TextField(blank=True, help_text='Необязательно. Карточка работает и без неё — только фото и имя гостя.', null=True, verbose_name='Цитата'),
        ),
    ]
