# Generated by Django 5.2 on 2026-09-05 15:56

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_guest_quote_alter_guest_quote_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='Квадратное фото. Аватары из соцсетей приходят небольшими — крупный портрет выглядит лучше.', keep_meta=True, null=True, quality=90, scale=None, size=[400, 400], upload_to='guests/', verbose_name='Фото'),
        ),
    ]
