# Generated by Django 5.2 on 2026-08-01 07:25

import ckeditor_uploader.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ky', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('content_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 1067], upload_to='about/', verbose_name='Изображение')),
                ('image_position', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='right', max_length=10, verbose_name='Положение изображения')),
            ],
            options={
                'verbose_name': 'Блок «О курорте»',
                'verbose_name_plural': 'Страница «О курорте»',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_en', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_ky', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO: keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('og_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1200, 630], upload_to='seo/', verbose_name='Изображение для соцсетей (OG)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Содержимое')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое')),
                ('content_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1920, 800], upload_to='pages/', verbose_name='Обложка')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='Показывать в подвале')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Показывать в меню')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы сайта',
                'ordering': ('order', 'id'),
            },
        ),
    ]
