# Generated by Django 5.2 on 2026-08-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Блок «О нас»', 'verbose_name_plural': 'Страница «О нас»'},
        ),
    ]
