# Generated by Django 5.2 on 2026-08-13 11:40

import ckeditor_uploader.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_aboutsection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('eyebrow', models.CharField(blank=True, help_text='Например: «Наш замысел».', max_length=120, verbose_name='Надпись над заголовком')),
                ('eyebrow_ru', models.CharField(blank=True, help_text='Например: «Наш замысел».', max_length=120, null=True, verbose_name='Надпись над заголовком')),
                ('eyebrow_en', models.CharField(blank=True, help_text='Например: «Наш замысел».', max_length=120, null=True, verbose_name='Надпись над заголовком')),
                ('eyebrow_ky', models.CharField(blank=True, help_text='Например: «Наш замысел».', max_length=120, null=True, verbose_name='Надпись над заголовком')),
                ('title', models.CharField(default='Миссия и цели', max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(default='Миссия и цели', max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(default='Миссия и цели', max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(default='Миссия и цели', max_length=255, null=True, verbose_name='Заголовок')),
                ('statement', models.TextField(blank=True, help_text='Одна-две ёмкие фразы. Выводится крупно, как цитата.', verbose_name='Миссия')),
                ('statement_ru', models.TextField(blank=True, help_text='Одна-две ёмкие фразы. Выводится крупно, как цитата.', null=True, verbose_name='Миссия')),
                ('statement_en', models.TextField(blank=True, help_text='Одна-две ёмкие фразы. Выводится крупно, как цитата.', null=True, verbose_name='Миссия')),
                ('statement_ky', models.TextField(blank=True, help_text='Одна-две ёмкие фразы. Выводится крупно, как цитата.', null=True, verbose_name='Миссия')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Необязательно: развёрнутое пояснение.', verbose_name='Текст под миссией')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Необязательно: развёрнутое пояснение.', null=True, verbose_name='Текст под миссией')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Необязательно: развёрнутое пояснение.', null=True, verbose_name='Текст под миссией')),
                ('content_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Необязательно: развёрнутое пояснение.', null=True, verbose_name='Текст под миссией')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 1067], upload_to='about/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Миссия и цели',
                'verbose_name_plural': 'Миссия и цели',
            },
        ),
        migrations.CreateModel(
            name='MissionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=255, verbose_name='Цель')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Цель')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Цель')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Цель')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Пояснение')),
                ('description_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Пояснение')),
                ('description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Пояснение')),
                ('description_ky', models.CharField(blank=True, max_length=500, null=True, verbose_name='Пояснение')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='cms.mission', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ('order', 'id'),
            },
        ),
    ]
