# Generated by Django 5.2 on 2026-08-01 07:25

import ckeditor_uploader.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=120, null=True, verbose_name='Название')),
                ('icon', models.FileField(blank=True, null=True, upload_to='rooms/amenities/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_en', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_ky', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO: keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('og_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1200, 630], upload_to='seo/', verbose_name='Изображение для соцсетей (OG)')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('kind', models.CharField(choices=[('standard', 'Стандарт'), ('semi_lux', 'Полулюкс'), ('lux', 'Люкс'), ('deluxe', 'Делюкс'), ('president', 'Президентский'), ('family', 'Семейный'), ('cottage', 'Коттедж'), ('villa', 'Вилла'), ('yurt', 'Юрта')], default='standard', max_length=20, verbose_name='Тип размещения')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('short_description_ky', models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 1067], upload_to='rooms/covers/', verbose_name='Обложка')),
                ('capacity_adults', models.PositiveSmallIntegerField(default=2, verbose_name='Взрослых (макс.)')),
                ('capacity_children', models.PositiveSmallIntegerField(default=0, verbose_name='Детей (макс.)')),
                ('area', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Площадь, м²')),
                ('beds', models.CharField(blank=True, max_length=255, verbose_name='Кровати')),
                ('beds_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кровати')),
                ('beds_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кровати')),
                ('beds_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кровати')),
                ('rooms_count', models.PositiveSmallIntegerField(default=1, verbose_name='Комнат')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Витринная цена. Точная цена на выбранные даты приходит из Shelter.', max_digits=10, verbose_name='Цена от, сом/ночь')),
                ('shelter_code', models.CharField(blank=True, db_index=True, help_text='Идентификатор категории номера в PMS Shelter. Без него бронирование недоступно.', max_length=64, verbose_name='Код категории в Shelter')),
                ('total_rooms', models.PositiveSmallIntegerField(default=0, help_text='Резервное значение, если Shelter недоступен.', verbose_name='Всего номеров категории')),
                ('is_bookable', models.BooleanField(default=True, verbose_name='Доступно к бронированию')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_categories', to='rooms.amenity', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Номера и жильё',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[1600, 1067], upload_to='rooms/gallery/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('alt_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст')),
                ('alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст')),
                ('alt_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фото номера',
                'verbose_name_plural': 'Фото номера',
                'ordering': ('order', 'id'),
            },
        ),
    ]
