# Generated by Django 5.2 on 2026-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tour_url',
            field=models.URLField(blank=True, help_text='Внешняя ссылка на виртуальный тур. Кнопка «3D-тур» появляется в шапке, подвале и в галерее, если поле заполнено.', max_length=1000, verbose_name='Ссылка на 3D-тур'),
        ),
    ]
