# Generated by Django 5.2 on 2026-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sitesettings_tour_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='popup_delay',
            field=models.PositiveSmallIntegerField(default=4, help_text='Даём гостю осмотреться. Рекомендуем 3–6 секунд.', verbose_name='Задержка перед показом, сек'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_enabled',
            field=models.BooleanField(default=False, help_text='Окно появляется только если есть действующие акции.', verbose_name='Показывать окно с акциями'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_limit',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Сколько акций показывать'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_repeat_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Сколько дней не показывать окно тому, кто его закрыл. 0 — показывать каждый раз.', verbose_name='Не показывать повторно, дней'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подпись в окне'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_title',
            field=models.CharField(blank=True, help_text='По умолчанию — «Специальные предложения».', max_length=255, verbose_name='Заголовок окна'),
        ),
    ]
