# Generated by Django 5.2 on 2026-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sitesettings_popup_delay_sitesettings_popup_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_2gis_url',
            field=models.URLField(blank=True, help_text='Открывается по клику на адрес.', max_length=500, verbose_name='Ссылка на 2ГИС'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_google_url',
            field=models.URLField(blank=True, help_text='Открывается по клику на адрес.', max_length=500, verbose_name='Ссылка на Google Maps'),
        ),
    ]
