# Generated by Django 5.2 on 2026-08-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sitesettings_map_2gis_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fd24_book_widget_id',
            field=models.CharField(blank=True, help_text='Модуль на странице бронирования.', max_length=64, verbose_name='ID виджета бронирования'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fd24_enabled',
            field=models.BooleanField(default=False, help_text='Включает внешний модуль бронирования вместо собственной формы поиска.', verbose_name='Использовать виджет FrontDesk24'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fd24_start_widget_id',
            field=models.CharField(blank=True, help_text='Форма поиска на главной. Идентификатор выдаёт FrontDesk24.', max_length=64, verbose_name='ID стартового виджета'),
        ),
    ]
