# Generated by Django 5.2 on 2026-08-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_sitesettings_fd24_book_widget_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='fd24_book_widget_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='fd24_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='fd24_start_widget_id',
        ),
    ]
