# Generated by Django 5.2 on 2026-08-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_sitesettings_fd24_book_widget_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_whatsapp',
            field=models.CharField(blank=True, help_text='Куда уходят заявки на бронирование. Если пусто — берётся общий WhatsApp.', max_length=255, verbose_name='WhatsApp ресепшена для заявок'),
        ),
    ]
