# Generated by Django 5.2 on 2026-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_sitesettings_booking_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='events_extras',
            field=models.TextField(blank=True, help_text='Выводится внизу страницы конференц-залов. Каждая строка — отдельный пункт; строка вида «Заголовок:» становится подзаголовком.', verbose_name='Питание и оборудование для мероприятий'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='events_extras_en',
            field=models.TextField(blank=True, help_text='Выводится внизу страницы конференц-залов. Каждая строка — отдельный пункт; строка вида «Заголовок:» становится подзаголовком.', null=True, verbose_name='Питание и оборудование для мероприятий'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='events_extras_ky',
            field=models.TextField(blank=True, help_text='Выводится внизу страницы конференц-залов. Каждая строка — отдельный пункт; строка вида «Заголовок:» становится подзаголовком.', null=True, verbose_name='Питание и оборудование для мероприятий'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='events_extras_ru',
            field=models.TextField(blank=True, help_text='Выводится внизу страницы конференц-залов. Каждая строка — отдельный пункт; строка вида «Заголовок:» становится подзаголовком.', null=True, verbose_name='Питание и оборудование для мероприятий'),
        ),
    ]
