name: baitur

services:
  db_baitur:
    image: postgres:14
    container_name: postgres_db_baitur
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data_baitur:/var/lib/postgresql/data
    networks:
      - baitur_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_baitur:
    image: redis:6
    container_name: redis_baitur
    restart: always
    networks:
      - baitur_network

  web_baitur:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_baitur
    restart: always
    command: sh -c "/entrypoint.sh && gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60"
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    depends_on:
      db_baitur:
        condition: service_healthy
      redis_baitur:
        condition: service_started
    ports:
      - "127.0.0.1:8091:8000"
    networks:
      - baitur_network

networks:
  baitur_network:
    driver: bridge

volumes:
  postgres_data_baitur:
