# Generated by Django 5.2 on 2026-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencehall',
            name='capacity_amphitheatre',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Амфитеатр, чел.'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='capacity_cabaret',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кабаре, чел.'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='capacity_conference',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Конференц-стол, чел.'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='capacity_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вместимость до, чел.'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='capacity_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Нижняя граница: с какого числа гостей зал имеет смысл брать.', null=True, verbose_name='Вместимость от, чел.'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='capacity_square',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квадрат, чел.'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='included',
            field=models.CharField(blank=True, help_text='Например: вода, ручка, бумага, столы, стулья с чехлами.', max_length=500, verbose_name='Что входит в стоимость'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='included_en',
            field=models.CharField(blank=True, help_text='Например: вода, ручка, бумага, столы, стулья с чехлами.', max_length=500, null=True, verbose_name='Что входит в стоимость'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='included_ky',
            field=models.CharField(blank=True, help_text='Например: вода, ручка, бумага, столы, стулья с чехлами.', max_length=500, null=True, verbose_name='Что входит в стоимость'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='included_ru',
            field=models.CharField(blank=True, help_text='Например: вода, ручка, бумага, столы, стулья с чехлами.', max_length=500, null=True, verbose_name='Что входит в стоимость'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='is_year_round',
            field=models.BooleanField(default=True, verbose_name='Работает круглогодично'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='price_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Аренда за день, сом'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='price_half_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Аренда за полдня, сом'),
        ),
        migrations.AddField(
            model_name='conferencehall',
            name='price_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Аренда за час, сом'),
        ),
    ]
