# Generated by Django 5.2 on 2026-08-01 07:25

import ckeditor_uploader.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Код')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Размер скидки')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('min_nights', models.PositiveSmallIntegerField(default=1, verbose_name='Минимум ночей')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма брони')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 — без ограничений', verbose_name='Лимит применений')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Использован раз')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('room_categories', models.ManyToManyField(blank=True, help_text='Пусто — действует на все категории.', related_name='promo_codes', to='rooms.roomcategory', verbose_name='Только для категорий')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_en', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_ky', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO: keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('og_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1200, 630], upload_to='seo/', verbose_name='Изображение для соцсетей (OG)')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ky', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 900], upload_to='offers/', verbose_name='Фото')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по акции, сом')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки, сом')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.promocode', verbose_name='Промокод')),
                ('room_categories', models.ManyToManyField(blank=True, related_name='offers', to='rooms.roomcategory', verbose_name='Применимо к категориям')),
            ],
            options={
                'verbose_name': 'Спецпредложение',
                'verbose_name_plural': 'Спецпредложения',
                'ordering': ('order', '-id'),
            },
        ),
    ]
