# Generated by Django 5.2 on 2026-08-01 07:25

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_en', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_description_ky', models.TextField(blank=True, null=True, verbose_name='SEO: description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO: keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('seo_keywords_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO: keywords')),
                ('og_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1200, 630], upload_to='seo/', verbose_name='Изображение для соцсетей (OG)')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 1067], upload_to='gallery/covers/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Галерея',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка (YouTube / mp4)')),
                ('poster', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 900], upload_to='gallery/videos/', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('embed_url', models.URLField(verbose_name='Ссылка для встраивания (iframe src)')),
                ('poster', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 900], upload_to='gallery/tours/', verbose_name='Превью')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': '3D-тур',
                'verbose_name_plural': '3D-туры',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[1920, 1280], upload_to='gallery/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('alt_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст')),
                ('alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст')),
                ('alt_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.galleryalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ('order', 'id'),
            },
        ),
    ]
